export { approvalAnatomy } from './approval.anatomy'
export type { ApprovalPart } from './approval.anatomy'
export { approvalIds, connect } from './approval.connect'
export type { ApprovalConnectOptions } from './approval.connect'
export type { ApprovalDecision, ApprovalEffect, ApprovalProps, ApprovalState, ApprovalWords } from './approval.types'
