// Barrel for convenience only. Real consumers should import the per-component
// entry points (`@ggary/core/select`) so bundlers can drop what they do not use.
export { createAnatomy } from './types'
export type { Anatomy, Dict, Normalizer } from './types'

export { reactNormalizer, svelteNormalizer, domNormalizer } from './normalize-props'
export type { DomProps } from './normalize-props'

export { createMachine, withEffects } from './machine'
export type { Machine, Reducer } from './machine'

export { uid } from './utils/id'
export { clampIndex, edgeEnabled, firstEnabled, lastEnabled, nextEnabled } from './utils/collection'
export type { CollectionOptions } from './utils/collection'
export { focusMenuItem, focusMenuTarget, focusTab, revealMenuTarget, rovingFocus } from './utils/focus'
export { mergeProps } from './utils/merge-props'
export { groupValidity } from './utils/group'
export { onFormReset } from './utils/form-reset'
export type { GroupContext } from './utils/group'
export { typeahead } from './utils/typeahead'
export { TONE_ICONS } from './utils/tone'
export { headingTag, liveAttrs } from './utils/region'
export type { HeadingLevel, LiveMode, RegionRank } from './utils/region'
export type { StatusTone } from './utils/tone'
export { attachMenubarKeys, matchesMnemonic, parseMnemonic } from './utils/mnemonic'
export type { MenubarKeyHandlers, Mnemonic } from './utils/mnemonic'
export { acceptedFiles, attachFileDrop } from './utils/file-drop'
export type { FileDropCallbacks } from './utils/file-drop'
export { attachScrub, scrubValue, setInputValue, SCRUB_PIXELS_PER_STEP } from './utils/scrub'
export type { ScrubInput } from './utils/scrub'
export { attachToolbarKeys, toolbarItems } from './utils/toolbar'
export { attachShellDrawer } from './utils/shell'
export type { ShellDrawerOptions } from './utils/shell'
export { attachAutosize } from './utils/autosize'
export type { Autosize, AutosizeOptions } from './utils/autosize'
export { attachDialog } from './utils/modal'
export type { AttachDialogOptions, AttachedDialog } from './utils/modal'
export { attachPopover, contentInsets, submenuOffsets } from './utils/popover'
export type { AttachPopoverOptions, AttachedPopover } from './utils/popover'
export { attachPositioner } from './utils/position'
export type { Placement, PositionOptions, VirtualElement } from './utils/position'
export { openLayerCount, trackDismissable, scrollIntoViewIfNeeded } from './utils/dismissable'
export type { DismissableOptions, DismissReason } from './utils/dismissable'

export * as avatar from './components/avatar'
export * as badge from './components/badge'
export * as banner from './components/banner'
export * as breadcrumbs from './components/breadcrumbs'
export * as button from './components/button'
export * as buttonGroup from './components/button-group'
export * as card from './components/card'
export * as checkbox from './components/checkbox'
export * as checkboxGroup from './components/checkbox-group'
export * as chip from './components/chip'
export * as choiceCard from './components/choice-card'
export * as chipGroup from './components/chip-group'
export * as dataGrid from './components/data-grid'
export * as dialog from './components/dialog'
export * as emptyState from './components/empty-state'
export * as field from './components/field'
export * as fileDrop from './components/file-drop'
export * as fieldset from './components/fieldset'
export * as input from './components/input'
export * as inputGroup from './components/input-group'
export * as menu from './components/menu'
export * as menubar from './components/menubar'
export * as nav from './components/nav'
export * as note from './components/note'
export * as numberField from './components/number-field'
export * as pagination from './components/pagination'
export * as panel from './components/panel'
export * as popover from './components/popover'
export * as radioGroup from './components/radio-group'
export * as rail from './components/rail'
export * as search from './components/search'
export * as segmentedControl from './components/segmented-control'
export * as select from './components/select'
export * as shell from './components/shell'
export * as skeleton from './components/skeleton'
export * as slider from './components/slider'
export * as spinner from './components/spinner'
export * as split from './components/split'
export * as statusBar from './components/status-bar'
export * as switchControl from './components/switch'
export * as steps from './components/steps'
export * as tabs from './components/tabs'
export * as toast from './components/toast'
export * as toolbar from './components/toolbar'
export * as textarea from './components/textarea'
export * as tooltip from './components/tooltip'
