// Barrel for convenience only. Real consumers should import the per-component
// entry points (`@ggary/core/select`) so bundlers can drop what they do not use.
export { createAnatomy } from './types'
export type { Anatomy, Dict, Normalizer } from './types'

export { reactNormalizer, svelteNormalizer, domNormalizer } from './normalize-props'
export type { DomProps } from './normalize-props'

export { createMachine, withEffects } from './machine'
export type { Machine, Reducer } from './machine'

export { uid } from './utils/id'
export { clampIndex, edgeEnabled, firstEnabled, lastEnabled, nextEnabled } from './utils/collection'
export type { CollectionOptions } from './utils/collection'
export { focusMenuItem, focusMenuTarget, revealMenuTarget, rovingFocus } from './utils/focus'
export { mergeProps } from './utils/merge-props'
export { groupValidity } from './utils/group'
export { onFormReset } from './utils/form-reset'
export type { GroupContext } from './utils/group'
export { typeahead } from './utils/typeahead'
export { attachAutosize } from './utils/autosize'
export type { Autosize, AutosizeOptions } from './utils/autosize'
export { attachDialog } from './utils/modal'
export type { AttachDialogOptions, AttachedDialog } from './utils/modal'
export { attachPopover, contentInsets, submenuOffsets } from './utils/popover'
export type { AttachPopoverOptions, AttachedPopover } from './utils/popover'
export { attachPositioner } from './utils/position'
export type { Placement, PositionOptions } from './utils/position'
export { openLayerCount, trackDismissable, scrollIntoViewIfNeeded } from './utils/dismissable'
export type { DismissableOptions, DismissReason } from './utils/dismissable'

export * as button from './components/button'
export * as checkbox from './components/checkbox'
export * as checkboxGroup from './components/checkbox-group'
export * as chip from './components/chip'
export * as chipGroup from './components/chip-group'
export * as dialog from './components/dialog'
export * as field from './components/field'
export * as fieldset from './components/fieldset'
export * as input from './components/input'
export * as menu from './components/menu'
export * as popover from './components/popover'
export * as radioGroup from './components/radio-group'
export * as select from './components/select'
export * as switchControl from './components/switch'
export * as textarea from './components/textarea'
export * as tooltip from './components/tooltip'
