// Importing this module registers the custom elements — hence "sideEffects".
import './components/button/button.element'
import './components/checkbox/checkbox.element'
import './components/chip/chip.element'
import './components/chip-group/chip-group.element'
import './components/dialog/dialog.element'
import './components/field/field.element'
import './components/fieldset/fieldset.element'
import './components/input/input.element'
import './components/popover/popover.element'
import './components/radio-group/radio-group.element'
import './components/select/select.element'
import './components/textarea/textarea.element'
import './components/tooltip/tooltip.element'

export { spread } from './spread'
export { GgButtonElement } from './components/button/button.element'
export { GgCheckboxElement, GgSwitchElement } from './components/checkbox/checkbox.element'
export { GgChipElement } from './components/chip/chip.element'
export { GgChipGroupElement } from './components/chip-group/chip-group.element'
export { GgDialogElement } from './components/dialog/dialog.element'
export { GgFieldElement } from './components/field/field.element'
export { GgFieldsetElement } from './components/fieldset/fieldset.element'
export { GgInputElement } from './components/input/input.element'
export { GgPopoverElement } from './components/popover/popover.element'
export { GgCheckboxGroupElement, GgRadioGroupElement } from './components/radio-group/radio-group.element'
export { GgSelectElement } from './components/select/select.element'
export { GgTextareaElement } from './components/textarea/textarea.element'
export { GgTooltipElement } from './components/tooltip/tooltip.element'
