// Importing this module registers the custom elements — hence "sideEffects".
import './components/avatar/avatar.element'
import './components/badge/badge.element'
import './components/banner/banner.element'
import './components/button/button.element'
import './components/card/card.element'
import './components/checkbox/checkbox.element'
import './components/chip/chip.element'
import './components/chip-group/chip-group.element'
import './components/dialog/dialog.element'
import './components/empty-state/empty-state.element'
import './components/field/field.element'
import './components/fieldset/fieldset.element'
import './components/input/input.element'
import './components/menu/menu.element'
import './components/menubar/menubar.element'
import './components/note/note.element'
import './components/panel/panel.element'
import './components/popover/popover.element'
import './components/radio-group/radio-group.element'
import './components/select/select.element'
import './components/skeleton/skeleton.element'
import './components/spinner/spinner.element'
import './components/tabs/tabs.element'
import './components/toast/toaster.element'
import './components/textarea/textarea.element'
import './components/tooltip/tooltip.element'

export { spread } from './spread'
export { GgAvatarElement, GgAvatarGroupElement } from './components/avatar/avatar.element'
export { GgBadgeElement } from './components/badge/badge.element'
export { GgBannerElement } from './components/banner/banner.element'
export { GgButtonElement } from './components/button/button.element'
export { GgCardElement } from './components/card/card.element'
export { GgEmptyStateElement } from './components/empty-state/empty-state.element'
export { GgNoteElement } from './components/note/note.element'
export { GgPanelElement } from './components/panel/panel.element'
export { GgCheckboxElement, GgSwitchElement } from './components/checkbox/checkbox.element'
export { GgChipElement } from './components/chip/chip.element'
export { GgChipGroupElement } from './components/chip-group/chip-group.element'
export { GgDialogElement, GgSheetElement } from './components/dialog/dialog.element'
export { GgFieldElement } from './components/field/field.element'
export { GgFieldsetElement } from './components/fieldset/fieldset.element'
export { GgInputElement } from './components/input/input.element'
export { GgMenuElement } from './components/menu/menu.element'
export { GgMenubarElement } from './components/menubar/menubar.element'
export { GgPopoverElement } from './components/popover/popover.element'
export { GgCheckboxGroupElement, GgRadioGroupElement } from './components/radio-group/radio-group.element'
export { GgSelectElement } from './components/select/select.element'
export { GgSkeletonElement } from './components/skeleton/skeleton.element'
export { GgSpinnerElement } from './components/spinner/spinner.element'
export { GgTabsElement } from './components/tabs/tabs.element'
export { GgToasterElement } from './components/toast/toaster.element'
// The queue is framework-free: re-exported so `toast()` comes from the same package as the region.
export { createToaster, toast, toaster } from '@ggary/core/toast'
export type { ToastOptions, ToastTone, Toaster } from '@ggary/core/toast'
export { GgTextareaElement } from './components/textarea/textarea.element'
export { GgTooltipElement } from './components/tooltip/tooltip.element'
