export { sliderAnatomy } from './slider.anatomy'
export type { SliderPart } from './slider.anatomy'
export { connect, sliderFill } from './slider.connect'
export type { SliderConnectOptions } from './slider.connect'
export type { SliderProps, SliderSize } from './slider.types'
