// Token compiler. Deliberately dependency-free and ~100 lines: you will want to
// read and change this, and Style Dictionary's config format is a worse place to
// express "our tokens" than plain JS is.
//
//   src/primitives.json  raw values, never referenced by a component
//   src/semantic.json    the light theme, expressed as {refs} into primitives
//   src/themes/*.json    theme overrides, same shape as semantic.json
//
// Output: dist/tokens.css (custom properties) + dist/index.ts (typed consts).
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const PREFIX = 'gg'
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'))

/** { a: { b: 1 } } -> { 'a.b': 1 } */
function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, key, out)
    else out[key] = v
  }
  return out
}

/** Resolve {color.brand.600} references against the primitive table. */
function resolve(value, primitives, seen = new Set()) {
  if (typeof value !== 'string') return value
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    if (seen.has(ref)) throw new Error(`Circular token reference: ${ref}`)
    if (!(ref in primitives)) throw new Error(`Unknown token reference: {${ref}}`)
    return resolve(primitives[ref], primitives, new Set([...seen, ref]))
  })
}

const cssVar = (path) => `--${PREFIX}-${path.replace(/\./g, '-')}`
const tsKey = (path) => path.replace(/[.-](\w)/g, (_, c) => c.toUpperCase())

const primitives = flatten(read('src/primitives.json'))
const semantic = flatten(read('src/semantic.json'))

// Primitives are emitted too: an app occasionally needs `--gg-color-brand-600`
// directly, and having them present makes theme authoring in devtools possible.
const block = (entries, indent = '  ') =>
  Object.entries(entries).map(([p, v]) => `${indent}${cssVar(p)}: ${resolve(v, primitives)};`).join('\n')

const themes = readdirSync(join(root, 'src/themes'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => [basename(f, '.json'), flatten(read(`src/themes/${f}`))])

const css = `/* GENERATED by packages/tokens/build.mjs — do not edit. */
:root {
${block(primitives)}

${block(semantic)}
}

${themes.map(([name, t]) => `[data-theme='${name}'] {\n${block(t)}\n}`).join('\n\n')}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${themes.filter(([n]) => n === 'dark').map(([, t]) => block(t, '    ')).join('\n')}
  }
}
`

// The TS export is intentionally *var references*, not resolved values: JS that
// needs a token should stay themeable. `tokens.bgAccent` -> 'var(--gg-bg-accent)'
const ts = `// GENERATED by packages/tokens/build.mjs — do not edit.
export const tokens = {
${Object.keys({ ...primitives, ...semantic }).map((p) => `  ${tsKey(p)}: 'var(${cssVar(p)})',`).join('\n')}
} as const

export type TokenName = keyof typeof tokens
export const themes = [${['light', ...themes.map(([n]) => n)].map((n) => `'${n}'`).join(', ')}] as const
export type ThemeName = (typeof themes)[number]
`

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(join(root, 'dist/tokens.css'), css)
writeFileSync(join(root, 'dist/index.ts'), ts)
console.log(
  `tokens: ${Object.keys(primitives).length} primitives, ${Object.keys(semantic).length} semantic, ` +
  `${themes.length} theme override(s) -> dist/`
)
