// GGarry's token compiler. Deliberately dependency-free and ~100 lines: you will
// want to read and change this, and Style Dictionary's config format is a worse
// place to express "our tokens" than plain JS is.
//
//   tokens/primitives.json  raw values, never referenced by a component
//   tokens/semantic.json    the light mode, expressed as {refs} into primitives
//   tokens/modes/*.json     mode overrides (dark), same shape as semantic.json
//
// Output: dist/tokens.css (custom properties) + dist/index.ts (typed consts).
//
// These are GGarry's PRIVATE tokens, prefixed --ggarry-*. Application code reads
// the public contract instead (--gg-*, see src/contract.css), so it keeps working
// when a project switches themes.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { join, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const PREFIX = 'ggarry'
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'))

/** { a: { b: 1 } } -> { 'a.b': 1 } */
function flatten(obj, prefix = '', out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    const key = prefix ? `${prefix}.${k}` : k
    if (v && typeof v === 'object' && !Array.isArray(v)) flatten(v, key, out)
    else out[key] = v
  }
  return out
}

/** Resolve {color.brand.600} references against the primitive table. */
function resolve(value, primitives, seen = new Set()) {
  if (typeof value !== 'string') return value
  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    if (seen.has(ref)) throw new Error(`Circular token reference: ${ref}`)
    if (!(ref in primitives)) throw new Error(`Unknown token reference: {${ref}}`)
    return resolve(primitives[ref], primitives, new Set([...seen, ref]))
  })
}

const cssVar = (path) => `--${PREFIX}-${path.replace(/\./g, '-')}`
const tsKey = (path) => path.replace(/[.-](\w)/g, (_, c) => c.toUpperCase())

const primitives = flatten(read('tokens/primitives.json'))
const semantic = flatten(read('tokens/semantic.json'))

// Primitives are emitted too: having them present makes theme authoring in
// devtools possible.
const block = (entries, indent = '  ') =>
  Object.entries(entries).map(([p, v]) => `${indent}${cssVar(p)}: ${resolve(v, primitives)};`).join('\n')

const modes = readdirSync(join(root, 'tokens/modes'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => [basename(f, '.json'), flatten(read(`tokens/modes/${f}`))])

const css = `/* GENERATED by packages/theme-ggarry/build.mjs — do not edit. */
:root {
${block(primitives)}

${block(semantic)}
}

${modes.map(([name, t]) => `[data-mode='${name}'] {\n${block(t)}\n}`).join('\n\n')}

@media (prefers-color-scheme: dark) {
  :root:not([data-mode='light']) {
${modes.filter(([n]) => n === 'dark').map(([, t]) => block(t, '    ')).join('\n')}
  }
}
`

// The TS export is intentionally *var references*, not resolved values: JS that
// needs a token should stay themeable. `tokens.bgAccent` -> 'var(--ggarry-bg-accent)'
const ts = `// GENERATED by packages/theme-ggarry/build.mjs — do not edit.
export const tokens = {
${Object.keys({ ...primitives, ...semantic }).map((p) => `  ${tsKey(p)}: 'var(${cssVar(p)})',`).join('\n')}
} as const

export type TokenName = keyof typeof tokens
export const modes = [${['light', ...modes.map(([n]) => n)].map((n) => `'${n}'`).join(', ')}] as const
export type ModeName = (typeof modes)[number]
`

mkdirSync(join(root, 'dist'), { recursive: true })
writeFileSync(join(root, 'dist/tokens.css'), css)
writeFileSync(join(root, 'dist/index.ts'), ts)
console.log(
  `ggarry tokens: ${Object.keys(primitives).length} primitives, ${Object.keys(semantic).length} semantic, ` +
  `${modes.length} mode override(s) -> dist/`
)
