// The glyph compiler, shared by the default set and by every theme's overrides.
//
// A glyph is an SVG file. It compiles to a CSS custom property holding a data URI:
//
//   svg/check.svg  ->  --gg-icon-check: url("data:image/svg+xml,...")
//
// and components draw it as a MASK filled with currentColor (see
// @ggary/structure/icon.css). The consequences are the point of the design:
//
//   · the glyph's colour is always a token, never baked into the SVG — the
//     stroke colour inside the file is irrelevant to a mask;
//   · a theme swaps a glyph by redeclaring one custom property, with no change to
//     markup and no JS;
//   · adapters render an empty <span data-icon="check"> and know nothing about
//     shapes, so a new glyph never touches three frameworks.
//
// An app compiles its own glyphs with the same function (`app: true`): they
// join the kit's names, and one named as a kit glyph replaces it. The rules a
// glyph is held to live in glyph.mjs, shared with defineIcons at runtime.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { checkGlyph, glyphMapping, glyphToken } from './glyph.mjs'

export function readGlyphs(srcDir) {
  const glyphs = readdirSync(srcDir)
    .filter((f) => f.endsWith('.svg'))
    .sort()
    .map((file) => {
      const name = basename(file, '.svg')
      return { name, svg: checkGlyph(name, readFileSync(join(srcDir, file), 'utf8')) }
    })
  if (glyphs.length === 0) throw new Error(`No .svg glyphs in ${srcDir}`)
  return glyphs
}


/**
 * @param {object} options
 * @param {string} options.srcDir     directory of .svg glyphs
 * @param {string} options.outCss     CSS file to write
 * @param {string} [options.outTs]    the kit's set: a TS file with the name list and
 *   the KitIconName type. An app's (`app: true`): a .d.ts that adds its names to
 *   @ggary/icons' IconRegistry, so IconName takes them.
 * @param {boolean} [options.mapping] emit the [data-icon=name] -> --gg-icon rules.
 *   The base set does this; a theme override only redeclares tokens, so it cannot
 *   introduce a name components do not know.
 * @param {boolean} [options.app] an app's own glyphs: mapped (they are new names,
 *   or replace the kit's), and typed through IconRegistry. Load the CSS unlayered —
 *   the kit's glyphs are in a layer, so the app's win whatever loads first.
 * @param {string} [options.banner]
 */
export function compileIcons({ srcDir, outCss, outTs, mapping = false, app = false, banner = '' }) {
  const glyphs = readGlyphs(srcDir)

  const css = [
    `/* GENERATED from ${srcDir.replace(/\\/g, '/').split('/').slice(-2).join('/')} — do not edit. ${banner} */`,
    ':root {',
    ...glyphs.map((g) => `  ${glyphToken(g.name, g.svg)}`),
    '}',
    ...(mapping || app ? ['', ...glyphs.map((g) => glyphMapping(g.name))] : []),
    '',
  ].join('\n')

  mkdirSync(dirname(outCss), { recursive: true })
  writeFileSync(outCss, css)

  if (outTs) {
    const ts = app
      ? [
          '// GENERATED by @ggary/icons compileIcons — do not edit.',
          "import '@ggary/icons'",
          '',
          "declare module '@ggary/icons' {",
          '  interface IconRegistry {',
          ...glyphs.map((g) => `    '${g.name}': true`),
          '  }',
          '}',
          '',
        ].join('\n')
      : [
          '// GENERATED by packages/icons/compile.mjs — do not edit.',
          `export const iconNames = [${glyphs.map((g) => `'${g.name}'`).join(', ')}] as const`,
          'export type KitIconName = (typeof iconNames)[number]',
          '',
        ].join('\n')
    mkdirSync(dirname(outTs), { recursive: true })
    writeFileSync(outTs, ts)
  }

  return glyphs.map((g) => g.name)
}
