// The glyph compiler, shared by the default set and by every theme's overrides.
//
// A glyph is an SVG file. It compiles to a CSS custom property holding a data URI:
//
//   svg/check.svg  ->  --gg-icon-check: url("data:image/svg+xml,...")
//
// and components draw it as a MASK filled with currentColor (see
// @ggary/structure/icon.css). The consequences are the point of the design:
//
//   · the glyph's colour is always a token, never baked into the SVG — the
//     stroke colour inside the file is irrelevant to a mask;
//   · a theme swaps a glyph by redeclaring one custom property, with no change to
//     markup and no JS;
//   · adapters render an empty <span data-icon="check"> and know nothing about
//     shapes, so a new glyph never touches three frameworks.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'

const NAME = /^[a-z][a-z0-9]*(-[a-z0-9]+)*$/

export function readGlyphs(srcDir) {
  const glyphs = readdirSync(srcDir)
    .filter((f) => f.endsWith('.svg'))
    .sort()
    .map((file) => {
      const name = basename(file, '.svg')
      if (!NAME.test(name)) throw new Error(`Icon name must be kebab-case: ${file}`)
      const svg = readFileSync(join(srcDir, file), 'utf8').replace(/\s+/g, ' ').trim()
      if (!/viewBox=/.test(svg)) throw new Error(`${file}: an icon needs a viewBox, or it cannot scale into its box`)
      if (/<(style|script|image|foreignObject)\b/i.test(svg)) {
        throw new Error(`${file}: styles, scripts and embedded images are not allowed in a glyph`)
      }
      return { name, svg }
    })
  if (glyphs.length === 0) throw new Error(`No .svg glyphs in ${srcDir}`)
  return glyphs
}

const token = (glyph) => `  --gg-icon-${glyph.name}: url("data:image/svg+xml,${encodeURIComponent(glyph.svg)}");`

/**
 * @param {object} options
 * @param {string} options.srcDir     directory of .svg glyphs
 * @param {string} options.outCss     CSS file to write
 * @param {string} [options.outTs]    TS file with the name list and the IconName type
 * @param {boolean} [options.mapping] emit the [data-icon=name] -> --gg-icon rules.
 *   Only the BASE set does this; a theme override only redeclares tokens, so it
 *   cannot introduce a name components do not know.
 * @param {string} [options.banner]
 */
export function compileIcons({ srcDir, outCss, outTs, mapping = false, banner = '' }) {
  const glyphs = readGlyphs(srcDir)

  const css = [
    `/* GENERATED from ${srcDir.replace(/\\/g, '/').split('/').slice(-2).join('/')} — do not edit. ${banner} */`,
    ':root {',
    ...glyphs.map(token),
    '}',
    ...(mapping
      ? ['', ...glyphs.map((g) => `[data-icon='${g.name}'] { --gg-icon: var(--gg-icon-${g.name}); }`)]
      : []),
    '',
  ].join('\n')

  mkdirSync(dirname(outCss), { recursive: true })
  writeFileSync(outCss, css)

  if (outTs) {
    const ts = [
      '// GENERATED by packages/icons/compile.mjs — do not edit.',
      `export const iconNames = [${glyphs.map((g) => `'${g.name}'`).join(', ')}] as const`,
      'export type IconName = (typeof iconNames)[number]',
      '',
    ].join('\n')
    mkdirSync(dirname(outTs), { recursive: true })
    writeFileSync(outTs, ts)
  }

  return glyphs.map((g) => g.name)
}
